### ISSUE TITLE
Cannot reshape array of size 896 into shape with multiple of 6272 elements with ONNX model

### ISSUE THREAD

**Issue by liuxu-github-ui** [jackwish/tflite2onnx#44]
Hi,

I had a tflite model (trained with Tensorflow 1.14) and tried to convert it to onnx model. 

It showed the error message "NotImplementedError: Unsupported TFLite OP: 14". May I know what is the cause of this error?

**Comment by jackwish** [comment]
Hi @liuxu-github-ui , this error happens because some TFLite operators are not supported by `tflite2onnx`. The `14` here is the op code of the TFLite op which can be parsed with https://raw.githubusercontent.com/jackwish/tflite/master/tflite/BuiltinOperator.py.

For your case, `14` is `LOGISTIC` which should have been enabled in `v0.3.1`. May I know which version are you using?

Btw, the latest API `getSupportedOperator` can be used to parse the operator name, for example as below.
```
>>> from tflite2onnx import getSupportedOperator
>>> getSupportedOperator(14)
'LOGISTIC'
```

**Comment by liuxu-github-ui** [comment]
Hi,

Thanks for your reply. I managed to convert tflite file to onnx file with the latest version (0.3.1). But when I import the onnx model into Unity,it showed another error "Unexpected error while evaluating model output Identity. System.ArgumentException: Cannot reshape array of size 896 into shape with multiple of 6272 elements". Do you what caused this error? Thanks.

**Comment by jackwish** [comment]
Well, in general, for an error like this, we need to deep dive into the TFLite and the ONNX model to figure out what's going on... As the first step, you can try to identify which of the `Reshape` triggers the error.
